### PR TITLE
Fix buffering for events that have mapped entities.

### LINKED ISSUE #311: Do not panic on invalid entity mapping inside events
I used panic because I thought that it's impossible to happen 😅 
But forgot to take visibility into account. It was reported that sending an event that contains an entity that isn't visible for a client causes crash. I think we should ignore this event and change the panic into a warning.

### PR DESCRIPTION
**Pull request by Shatur**
Closes #311.

### CODE REVIEW

File: src/core/event_registry/server_event.rs [hunk 1]
```diff
@@ -387,7 +387,17 @@ impl ServerEvent {
     ) -> bincode::Result<E> {
         self.check_type::<E>();
         let deserialize: DeserializeFn<E> = std::mem::transmute(self.deserialize);
-        (deserialize)(ctx, cursor)
+        let event = (deserialize)(ctx, cursor);
+        if ctx.invalid_entities.is_empty() {
```
[the remark this answers is not in the document]
Comment (Shatur) [reply src/core/event_registry/server_event.rs:391]: Ah, right, good catch!

**Comment by Shatur** [comment]
Fixed the bug reported by @NiseVoid in Discord.
Pushed it here since it touches the same code.

After the events refactor I map the event inside the deserialization function. But I need to deserialize the tick first and compare it for buffering. We didn't catch it in the tests because we didn't have a test for the combination of event buffering **and** entity mapping.

The fix is simple. The event queue is not generic now and stored the event in its serialized form. Now initialized inside the `ClientPlugin`. We deserialize the tick first, do comparsion and push the event to the queue if it's smaller.

File: src/client/events.rs [hunk 2]
```diff
@@ -83,36 +84,31 @@ impl ClientEventsPlugin {
             world.resource_scope(|world, registry: Mut<AppTypeRegistry>| {
                 world.resource_scope(|world, entity_map: Mut<ServerEntityMap>| {
                     world.resource_scope(|world, event_registry: Mut<EventRegistry>| {
-                        let init_tick = **world.resource::<ServerInitTick>();
-                        let mut ctx = ClientReceiveCtx {
-                            registry: &registry.read(),
-                            entity_map: &entity_map,
-                        };
+                        world.resource_scope(|world, mut queue: Mut<ServerEventQueue>| {
```
Comment (Shatur) [inline src/client/events.rs:87]: The diff is messy, but I just added a new scope for `ServerEventQueue`.

File: src/client/events.rs [hunk 3]
```diff
@@ -83,36 +84,31 @@ impl ClientEventsPlugin {
...
+                            let init_tick = **world.resource::<ServerInitTick>();
+                            let mut ctx = ClientReceiveCtx {
+                                registry: &registry.read(),
+                                entity_map: &entity_map,
+                                invalid_entities: Vec::new(),
+                            };
 
-                        let world_cell = world.as_unsafe_world_cell();
-                        for event_data in event_registry.iter_server_events() {
-                            // SAFETY: both resources mutably borrowed uniquely.
```
Comment (Shatur) [inline src/client/events.rs:94]: No longer need to be unsafe since we borrow only one resource.
